from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ModelMetadata(BaseModel):
    """
    Metadata describing an available LLM.
    """
    id: str = Field(..., description="Unique model identifier (Ollama model ID)")
    display_name: str = Field(..., description="User-facing display name")
    description: str = Field(..., description="Brief description of capabilities")

class GroundedAnswerResponse(BaseModel):
    """
    Structured response returned by the AI Answer Generation Layer.
    """
    answer: str = Field(..., description="The grounded answer generated by the LLM")
    used_chunk_ids: List[str] = Field(default_factory=list, description="IDs of the chunks used to generate the answer")
    page_references: List[int] = Field(default_factory=list, description="1-indexed page numbers referenced by the used chunks")
    image_references: List[Dict[str, Any]] = Field(default_factory=list, description="Metadata and URLs of images/figures referenced or used as evidence")
    retrieval_statistics: Dict[str, Any] = Field(default_factory=dict, description="Statistics about the retrieval process (e.g. chunk counts, scores)")
    generation_time: float = Field(0.0, description="Time taken for answer generation in seconds")
    selected_model: str = Field(..., description="The ID of the model selected/used for generation")
    requested_model: Optional[str] = Field(None, description="Original model ID requested by the user")
    fallback_triggered: bool = Field(False, description="Whether automatic fallback to the default model occurred")
    fallback_reason: Optional[str] = Field(None, description="Reason for automatic fallback if triggered")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata about the response")
